openapi: 3.0.3
info:
  title: Barcoder reader 
  description: |-
    Проектная работа OTUS
    
    - [Github репозиторий](https://github.com/dm1tru/barcoder)
    
  version: 1.0.1

servers:
  - url: http://barcoder.ds4.ru/api/
tags:
  - name: device
    description: Работа с устройствами
   
  - name: code
    description: Работа со штрих-кодами

 
paths:
  /devices:
    get:
      tags:
        - device
      summary: Список устройств
      description: Возвращает список устройств
      operationId: getDevices
      responses:
        '200':
          description: successful operation
          content:
            application/json:
             schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        
      security:
        - api_key: []
  /devices/{id}:
    get:
      tags:
        - device
      summary: Свойства устройства
      description: Возвращает информацию об устройстве
      operationId: getDeviceId
      parameters:
        - name: id
          in: path
          description: ID устройства
          required: true
          schema:
            type: integer
  
      responses:
        '200':
          description: successful operation
          content:
            application/json:
             schema:
               $ref: '#/components/schemas/Device'
        
      security:
        - api_key: []        
        
  /codes:
    get:
      tags:
        - code
      summary: Список штрих-кодов
      description: Возвращает список штрих-кодов
      operationId: getCodes
      parameters:
        - name: start_id
          in: query
          description: 'Начальный ID'
          required: false
          schema:
            type: integer
        - name: end_id
          in: query
          description: 'Конечный ID'
          required: false
          schema:
            type: integer
        - name: device_id
          in: query
          description: 'ID устройства'
          required: false
          schema:
            type: integer
        - name: start_date
          in: query
          description: 'Unix дата начала'
          required: false
          schema:
            type: integer   
        - name: end_date
          in: query
          description: 'Unix дата окончания'
          required: false
          schema:
            type: integer        
        - name: limit
          in: query
          description: 'Лимит'
          default: 100
          required: false
          schema:
            type: integer   
        - name: offset
          in: query
          description: 'Смещение'
          default: 0
          required: false
          schema:
            type: integer              
      responses:
        '200':
          description: Успешное выполнение
          content:
            application/json:
             schema:
                type: array
                items:
                  $ref: '#/components/schemas/Code'
      security:
        - api_key: []
    put:
      tags:
        - code
      summary: Добавление нового штрих-кода
      description: 'Осуществляет добавление нового штрих-кода'
      operationId: addCode
      parameters:
        - name: device_id
          in: query
          description: ID устройства
          required: true
          schema:
            type: integer
        - name: code
          in: query
          description: Штрихкод
          required: true
          schema:
            type: string
        - name: date
          in: query
          description: Unix дата создания
          schema:
            type: integer
        - name: count
          in: query
          description: Количество
          default: 1
          schema:
            type: integer    
      responses:
         '200':
          description: Успешное выполнение
          content:
            application/json:
             schema:
                type: array
                items:
                  $ref: '#/components/schemas/Code'
      security:
        - api_key: []    
       
  
 
components:
  schemas:
    Device:
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: device name
        host:
          type: string
          example: "%"
        order:
          type: integer
          example: 1000
    Code:
      properties:
        id:
          type: integer
          format: int64
          example: 10
        code:
          type: string
          example: xxxxxxxx
        count:
          type: integer
          example: 1         
        date:
          type: integer
          example: "1715631548"
        device_id:
          type: integer
          example: 1
  
   
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Api-Key
      in: header